"""
Sprint 064c: H/G-inv Ratio Analysis for Z_q Symmetry at d=q

Sprint 034 established that H/G-inv ratio (Hamiltonian operator dimension /
G-invariant operator dimension) predicts BW locality ordering.

Prior data (Sprint 034, n_A=4 for d=2, n_A=3 for d=3):
  U(1) d=2: H/G-inv=0.143, BW=100%
  Z_2  d=2: H/G-inv=0.099, BW=91%
  S_3  d=3: H/G-inv=0.072, BW=76.5%
  Z_3  d=3: H/G-inv=0.040, BW=69.7%

Now extend to Z_q at d=q for q=4,5,7,10. The Potts model at q>=4 has Z_q
symmetry (not S_q — the permutation X+X^dag only generates cyclic group).

Method: Count Z_q-invariant operators on n_A sites with local dim q.
An operator O is Z_q-invariant iff X_total^k O (X_total^k)^dag = O for all k.
Equivalently, project the full operator space onto the Z_q-invariant subspace
using group averaging: P_inv = (1/q) sum_k (X_total^k) . O . (X_total^{-k}).

Count dimensions, compute H/G-inv, predict BW locality ordering.
"""

import numpy as np
from scipy import linalg as la
import json, time

t0 = time.time()

def count_zq_invariant_ops(q, n_A):
    """
    Count Z_q-invariant traceless operators on n_A sites, each dim q.
    Z_q generated by cyclic permutation X = sum_a |a+1><a| on each site.
    Total symmetry: X_total = X^{otimes n_A}.

    Method: An operator O (in the q^n_A x q^n_A space) is Z_q-invariant iff
    [X_total, O] = 0. Count dimension of commutant of X_total.

    X_total has eigenvalues omega^m where omega=e^{2pi i/q} and m is the
    total Z_q charge (sum of site charges mod q).

    The invariant operators are block-diagonal in the charge sectors.
    dim(invariant) = sum_m dim(sector_m)^2.
    """
    dim = q**n_A

    # Build total charge for each basis state
    # Basis state |s_0, s_1, ..., s_{n_A-1}> has charge sum(s_i) mod q
    charges = np.zeros(dim, dtype=int)
    for idx in range(dim):
        total_charge = 0
        temp = idx
        for site in range(n_A):
            total_charge += temp % q
            temp //= q
        charges[idx] = total_charge % q

    # Count dimension of each charge sector
    sector_dims = {}
    for m in range(q):
        sector_dims[m] = int(np.sum(charges == m))

    # Invariant operator dimension = sum of sector_dim^2
    # (operators that are block-diagonal in charge sectors)
    total_inv = sum(d**2 for d in sector_dims.values())

    # Subtract 1 for traceless (identity is invariant)
    total_inv_tl = total_inv - 1

    # Total traceless operators
    total_tl = dim**2 - 1

    return total_inv_tl, total_tl, sector_dims

def count_hamiltonian_terms(q, n_A):
    """
    Count independent Hamiltonian-type operators (Potts terms in subsystem A).
    Bond terms: delta(s_i, s_{i+1}) for i=0,...,n_A-2 → (n_A-1) operators
    Site terms: (X_i + X_i^dag) for i=0,...,n_A-1 → n_A operators
    Total: 2*n_A - 1
    But we need traceless versions. Each operator minus its trace is 1 independent op.
    """
    return (n_A - 1) + n_A  # bonds + sites

def verify_counting_small(q, n_A):
    """
    Verify counting by explicit construction for small cases.
    Build X_total, check commutant dimension.
    """
    dim = q**n_A

    # Build X_total = X ⊗ X ⊗ ... ⊗ X
    X_single = np.zeros((q, q))
    for a in range(q):
        X_single[(a+1) % q, a] = 1.0

    X_total = np.eye(1)
    for _ in range(n_A):
        X_total = np.kron(X_total, X_single)

    # Group averaging projector: P(O) = (1/q) sum_k X^k O X^{-k}
    # Count invariant operators by projecting a basis
    # Standard operator basis: E_{ij} (dim^2 operators)
    # Count how many independent operators survive projection

    # More efficient: eigendecompose X_total
    eigvals, eigvecs = la.eig(X_total)
    # Round eigenvalues to omega^k
    omega = np.exp(2j * np.pi / q)
    charges_eig = np.zeros(dim, dtype=int)
    for i in range(dim):
        for k in range(q):
            if abs(eigvals[i] - omega**k) < 1e-10:
                charges_eig[i] = k
                break

    # Count sector dimensions
    sector_dims = {}
    for k in range(q):
        sector_dims[k] = int(np.sum(charges_eig == k))

    inv_dim = sum(d**2 for d in sector_dims.values()) - 1  # traceless
    return inv_dim, sector_dims

# ---- Main computation ----
print("=== Sprint 064c: H/G-inv Ratio for Z_q Potts ===\n")

# Compute for various q at n_A=3 and n_A=4 where feasible
results = {}

for q in [2, 3, 4, 5, 7, 10]:
    results[q] = {}
    for n_A in [3, 4]:
        dim = q**n_A
        if dim > 100000:
            print(f"  q={q}, n_A={n_A}: dim={dim} too large, skipping explicit verification")
            # Use counting formula only
            inv_tl, total_tl, sector_dims = count_zq_invariant_ops(q, n_A)
            h_terms = count_hamiltonian_terms(q, n_A)
            h_ginv = h_terms / inv_tl
            results[q][n_A] = {
                'inv_tl': inv_tl, 'total_tl': total_tl,
                'h_terms': h_terms, 'h_ginv': h_ginv,
                'sector_dims': {str(k): v for k, v in sector_dims.items()},
                'verified': False
            }
            print(f"  q={q}, n_A={n_A}: Z_q-inv={inv_tl}/{total_tl} ({inv_tl/total_tl*100:.1f}%), "
                  f"H_terms={h_terms}, H/G-inv={h_ginv:.4f}")
            continue

        t1 = time.time()
        inv_tl, total_tl, sector_dims = count_zq_invariant_ops(q, n_A)
        h_terms = count_hamiltonian_terms(q, n_A)

        # Verify with explicit computation for small cases
        if dim <= 10000:
            inv_verify, sectors_verify = verify_counting_small(q, n_A)
            match = (inv_verify == inv_tl)
            print(f"  q={q}, n_A={n_A}: counting={inv_tl}, explicit={inv_verify}, match={match}")
        else:
            match = None

        h_ginv = h_terms / inv_tl
        dt = time.time() - t1

        results[q][n_A] = {
            'inv_tl': inv_tl, 'total_tl': total_tl,
            'h_terms': h_terms, 'h_ginv': h_ginv,
            'sector_dims': {str(k): v for k, v in sector_dims.items()},
            'verified': match, 'time_s': dt
        }
        print(f"  q={q}, n_A={n_A}: Z_q-inv={inv_tl}/{total_tl} ({inv_tl/total_tl*100:.1f}%), "
              f"H_terms={h_terms}, H/G-inv={h_ginv:.4f} [{dt:.1f}s]")

# ---- Comparison table ----
print("\n" + "="*70)
print("H/G-inv RATIO vs MEASURED BW LOCALITY")
print("="*70)

# BW data from Sprints 032-034 and 064a,b
# Use consistent n_A=4 for q=2-5, n_A=3 for q=7,10
bw_data = {
    2: {'bw_peak': 91.0, 'n_A': 4, 'sym': 'Z_2', 'source': 'Sprint 032'},
    3: {'bw_peak': 76.5, 'n_A': 4, 'sym': 'S_3/Z_3', 'source': 'Sprint 033'},
    4: {'bw_peak': 56.0, 'n_A': 4, 'sym': 'Z_4', 'source': 'Sprint 064a'},
    5: {'bw_peak': 42.3, 'n_A': 4, 'sym': 'Z_5', 'source': 'Sprint 064b'},
    7: {'bw_peak': 69.4, 'n_A': 3, 'sym': 'Z_7', 'source': 'Sprint 064b'},
    10: {'bw_peak': 51.2, 'n_A': 3, 'sym': 'Z_10', 'source': 'Sprint 064b'},
}

print(f"\n{'q':>3} {'Sym':>6} {'n_A':>3} {'G-inv':>8} {'Total':>8} {'G-inv%':>7} {'H_terms':>7} {'H/G-inv':>8} {'BW peak':>8}")
print("-" * 70)

for q in [2, 3, 4, 5, 7, 10]:
    bd = bw_data[q]
    nA = bd['n_A']
    r = results[q][nA]
    print(f"{q:>3} {bd['sym']:>6} {nA:>3} {r['inv_tl']:>8} {r['total_tl']:>8} "
          f"{r['inv_tl']/r['total_tl']*100:>6.1f}% {r['h_terms']:>7} {r['h_ginv']:>8.5f} {bd['bw_peak']:>7.1f}%")

# ---- Check monotonicity at fixed n_A ----
print("\n=== Fixed n_A=4 (q=2-5): Fair comparison ===")
print(f"{'q':>3} {'H/G-inv':>10} {'BW peak':>10}")
for q in [2, 3, 4, 5]:
    if 4 in results[q]:
        r = results[q][4]
        print(f"{q:>3} {r['h_ginv']:>10.5f} {bw_data[q]['bw_peak']:>9.1f}%")

print("\n=== Fixed n_A=3 (q=2-10): ===")
print(f"{'q':>3} {'H/G-inv':>10} {'BW peak (n_A matched)':>22}")
for q in [2, 3, 4, 5, 7, 10]:
    if 3 in results[q]:
        r = results[q][3]
        bw = bw_data[q]['bw_peak'] if bw_data[q]['n_A'] == 3 else '(n_A=4)'
        print(f"{q:>3} {r['h_ginv']:>10.5f}   {bw}")

# ---- Scaling law for H/G-inv ----
print("\n=== H/G-inv Scaling with q (n_A=3) ===")
q_vals = []
hginv_vals = []
for q in [2, 3, 4, 5, 7, 10]:
    r = results[q][3]
    q_vals.append(q)
    hginv_vals.append(r['h_ginv'])
    print(f"  q={q}: H/G-inv = {r['h_ginv']:.5f}")

# Fit: H/G-inv ~ a / q^b
q_arr = np.array(q_vals, dtype=float)
hg_arr = np.array(hginv_vals)
log_q = np.log(q_arr)
log_hg = np.log(hg_arr)
b, log_a = np.polyfit(log_q, log_hg, 1)
a = np.exp(log_a)
print(f"\nPower law fit: H/G-inv ≈ {a:.3f} / q^{-b:.3f}")
for q_test in q_vals:
    pred = a * q_test**b
    actual = results[q_test][3]['h_ginv']
    print(f"  q={q_test}: predicted={pred:.5f}, actual={actual:.5f}, error={abs(pred-actual)/actual*100:.1f}%")

# ---- Save ----
save_data = {
    'experiment': '064c',
    'description': 'H/G-inv ratio for Z_q symmetry at d=q',
    'results': {},
    'scaling_fit': {'a': float(a), 'b': float(b)},
    'runtime_seconds': time.time() - t0
}
for q in results:
    save_data['results'][str(q)] = {}
    for nA in results[q]:
        r = results[q][nA]
        save_data['results'][str(q)][str(nA)] = {
            'inv_tl': r['inv_tl'], 'total_tl': r['total_tl'],
            'h_terms': r['h_terms'], 'h_ginv': r['h_ginv']
        }

with open('results/sprint_064c_hginv_ratio.json', 'w') as f:
    json.dump(save_data, f, indent=2)

print(f"\nSaved. Runtime: {time.time()-t0:.1f}s")
